enableSearch = true

copyright = "Â© { year } kazutamu"

[params]
  mainSections = ["posts"]

[params.homepage]
  showRecent = true
  recentLimit = 5
  layout = "background"
  homepageImage = "/images/kazutamu_001.JPG"

[footer]
showThemeAttribution = false

[article]
showTableOfContents = true
showWordCount = false
showReadingTime = false