enableSearch = true

copyright = "Â© { year } kazutamu"

mainSections = ["posts"]

[footer]
showThemeAttribution = false

[article]
showTableOfContents = true
showWordCount = false
showReadingTime = false