enableSearch = true

copyright = "Â© { year } kazutamu"

[params]
  mainSections = ["posts"]

[params.homepage]
  showRecent = true
  recentLimit = 5

[footer]
showThemeAttribution = false

[article]
showTableOfContents = true
showWordCount = false
showReadingTime = false